# Generated by ChatGPT
from django.db import migrations, models


def copy_texts(apps, schema_editor):
    Location = apps.get_model("game", "Location")
    Mission = apps.get_model("game", "Mission")
    for loc in Location.objects.all():
        updated_fields = []
        if not loc.title_en:
            loc.title_en = loc.title or ""
            updated_fields.append("title_en")
        if not loc.title_ru:
            loc.title_ru = loc.title or ""
            updated_fields.append("title_ru")
        if not loc.description_en:
            loc.description_en = loc.description or ""
            updated_fields.append("description_en")
        if not loc.description_ru:
            loc.description_ru = loc.description or ""
            updated_fields.append("description_ru")
        if updated_fields:
            loc.save(update_fields=updated_fields)
    for mission in Mission.objects.all():
        updated_fields = []
        if not mission.title_en:
            mission.title_en = mission.title or ""
            updated_fields.append("title_en")
        if not mission.title_ru:
            mission.title_ru = mission.title or ""
            updated_fields.append("title_ru")
        if not mission.description_en:
            mission.description_en = mission.description or ""
            updated_fields.append("description_en")
        if not mission.description_ru:
            mission.description_ru = mission.description or ""
            updated_fields.append("description_ru")
        if updated_fields:
            mission.save(update_fields=updated_fields)


def noop_reverse(apps, schema_editor):
    # No-op reverse migration; localized fields can stay populated.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_mission_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="description_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="location",
            name="description_ru",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="location",
            name="title_en",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="location",
            name="title_ru",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="mission",
            name="description_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="description_ru",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="title_en",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="mission",
            name="title_ru",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(copy_texts, noop_reverse),
    ]
