# Generated by ChatGPT
from django.db import migrations, models


def seed_default_track(apps, schema_editor):
    Track = apps.get_model("game", "Track")
    Location = apps.get_model("game", "Location")
    track, _ = Track.objects.get_or_create(
        slug="python-path",
        defaults={
            "title": "Python Path",
            "title_ru": "Путь Python",
            "description": "Foundation journey for complete beginners.",
            "description_ru": "Базовый путь от новичка до Python-разработчика.",
            "tagline_en": "From zero to confident Python apprentice.",
            "tagline_ru": "От полного нуля до уверенного ученика Python.",
            "color_theme": "#7dd3fc",
            "order": 1,
        },
    )
    Location.objects.filter(track__isnull=True).update(track=track)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_localized_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("title_en", models.CharField(blank=True, max_length=200)),
                ("title_ru", models.CharField(blank=True, max_length=200)),
                ("description_en", models.TextField(blank=True)),
                ("description_ru", models.TextField(blank=True)),
                ("tagline_en", models.CharField(blank=True, max_length=255)),
                ("tagline_ru", models.CharField(blank=True, max_length=255)),
                ("icon_url", models.URLField(blank=True)),
                ("banner_url", models.URLField(blank=True)),
                ("color_theme", models.CharField(blank=True, max_length=32)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_premium", models.BooleanField(default=False)),
                ("default_language", models.CharField(default="ru", max_length=5)),
            ],
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="location",
            name="track",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name="worlds", to="game.track"),
        ),
        migrations.RunPython(seed_default_track, noop_reverse),
    ]
