# Generated by Django 4.2.30 on 2026-05-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_intro',
            field=models.BooleanField(default=False, help_text='Вводный курс. Пока пользователь не пройдёт все миссии этого трека, выбор класса заблокирован. Включать стоит ровно у одного активного трека.'),
        ),
    ]
