# Generated by Django 4.2.30 on 2026-06-04 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0010_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Преподаватель-владелец курса (Студия). Пусто = системный/seed-курс, редактируется только суперюзером.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
