# Generated by Django 4.2.30 on 2026-09-29 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0011_track_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('mission_started', 'Mission started'), ('mission_completed', 'Mission completed'), ('task_opened', 'Task opened'), ('task_submitted', 'Story/quiz step submitted'), ('hint_used', 'Hint scroll used'), ('skeleton_used', 'Skeleton scroll used'), ('ai_hint_used', 'AI hint used'), ('ai_mentor_used', 'AI mentor used')], max_length=32)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='game.mission')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='game.missiontask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='game_learni_user_id_657b14_idx'), models.Index(fields=['event_type', 'created_at'], name='game_learni_event_t_5aa443_idx')],
            },
        ),
        migrations.CreateModel(
            name='CodeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('success', 'Ran and (if graded) passed'), ('wrong_output', 'Ran fine but the output did not match'), ('error', 'Crashed or exited with a non-zero code'), ('timeout', 'Killed by the time limit'), ('output_limit', 'Killed for printing too much'), ('runner_error', "Sandbox failure, not the learner's fault")], max_length=16)),
                ('error_type', models.CharField(blank=True, help_text='Exception class, e.g. NameError.', max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=200)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('code_length', models.PositiveIntegerField(default=0)),
                ('stdout_size', models.PositiveIntegerField(default=0)),
                ('stderr_size', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(blank=True, help_text='Null when the run was not graded.', null=True)),
                ('attempt_no', models.PositiveIntegerField(blank=True, help_text="The task's attempt counter after this run (graded runs only).", null=True)),
                ('after_solved', models.BooleanField(default=False, help_text="The task was already solved before this run (re-run for fun): leave such runs out of 'attempts to success'.")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('task', models.ForeignKey(blank=True, help_text='Empty for free practice runs outside a task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_runs', to='game.missiontask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='game_coderu_user_id_99995b_idx'), models.Index(fields=['task', 'created_at'], name='game_coderu_task_id_2bd63a_idx')],
            },
        ),
    ]
