# Generated by Django 4.2.30 on 2026-09-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_learning_footprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningevent',
            name='event_type',
            field=models.CharField(choices=[('login', 'Login'), ('mission_started', 'Mission started'), ('mission_completed', 'Mission completed'), ('task_opened', 'Task opened'), ('task_submitted', 'Story/quiz step submitted'), ('hint_used', 'Hint scroll used'), ('skeleton_used', 'Skeleton scroll used'), ('ai_hint_used', 'AI hint used'), ('ai_mentor_used', 'AI mentor used'), ('help_offered', 'Help offered after repeated failures')], max_length=32),
        ),
    ]
