# Generated by Django 4.2.30 on 2026-09-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_help_offered_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missiontask',
            name='is_side_quest',
        ),
        migrations.RemoveField(
            model_name='track',
            name='default_language',
        ),
        migrations.RemoveField(
            model_name='track',
            name='is_premium',
        ),
    ]
