# Generated by Django 4.2.30 on 2026-05-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_class_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_summons',
            field=models.PositiveIntegerField(default=3, help_text='Количество вызовов AI-помощника (AI Summon Item)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hint_scrolls',
            field=models.PositiveIntegerField(default=5, help_text='Зелья ясности (Hint Scroll - подсветка синтаксиса/ошибок)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skeleton_scrolls',
            field=models.PositiveIntegerField(default=3, help_text='Свитки Архитектора (Skeleton Scroll - вставка стартового кода)'),
        ),
    ]
