# Generated by Django 4.2.30 on 2026-06-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_streak_date',
            field=models.DateField(blank=True, help_text='Дата последнего засчитанного в стрик дня', null=True),
        ),
    ]
