# Generated by Django 4.2.30 on 2026-06-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_last_streak_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_streak_reminder',
            field=models.DateField(blank=True, help_text='Дата последнего email-напоминания о стрике', null=True),
        ),
    ]
