# Generated by Django 4.2.30 on 2026-09-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_last_streak_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='research_consent',
            field=models.BooleanField(default=False, help_text='Согласие на использование учебной активности в исследовании'),
        ),
        migrations.AddField(
            model_name='profile',
            name='research_consent_at',
            field=models.DateTimeField(blank=True, help_text='Когда согласие дано или отозвано в последний раз', null=True),
        ),
    ]
