# Generated by Django 4.2.30 on 2026-09-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_email_verification_pending'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
